---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3885250878-dmLmP8h2Ob3jpWcxlSeXJfPDS4dWQAI2uA4N12s
:access_token_secret: aIvoiZN9zgA7aGRrGssgrErmuc0Uha5OEFGycVR36NEPe
